name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
env:
  CI: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: SSH into Server and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_KEY_PASSPHRASE }}
          port: 22
          script: |
            cd grhotel/backend-server/grpos-backend
            git pull https://${{ secrets.SERVER_GIT_USERNAME }}:${{ secrets.SERVER_TOKEN }}@github.com/AxraTech/grpos-backend.git
            cd ../../
            docker-compose build gr-hotel-backend
            docker-compose down
            docker-compose up -d
            docker system prune -af
